"""Init2

Revision ID: 6b9182adf204
Revises: e6f85de973dc
Create Date: 2023-06-30 14:57:34.409147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9182adf204'
down_revision = 'e6f85de973dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
